name: CI/CD Docker Deploy

on:
  push:
    branches:
      - main  # Run on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t usermah/my-nginx-site:latest .

      # Push the image
      - name: Push Docker image
        run: |
          docker push usermah/my-nginx-site:latest
